[project]
name = "todo-cli"
version = "0.1.0"
requires-python = ">=3.10"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I","B"]

[tool.pytest.ini_options]
addopts = "-q --cov=src/todo_cli --cov-report=term-missing"
